### ISSUE TITLE
在Linux机器可以使用这个吗？

### ISSUE THREAD

**Issue by Moe-New** [cnnblike/discord-lite#3]
没有Windows机器，要怎么办呢...

**Comment by cnnblike** [comment]
Was busy these days, wait for a few days plz.
![qq20180811-0](https://user-images.githubusercontent.com/5412263/45874350-7d76cc80-bd49-11e8-83fa-575f3d59fde5.jpg)

**Comment by laozhao1** [comment]
ok....
